### ISSUE TITLE
Password as environment variable

### ISSUE THREAD

**Issue by sfali** [zalando/spring-cloud-config-aws-kms#48] opened 2018-10-22 23:50 UTC
Hi There,

Is it possible  to pass encrypted password as environment variable?

I have following deceleration in `application.properties`:

`spring.datasource.password={cipher}${MYSQL_PASSWORD} `

This seem to be not working.

Regards,

Syed

**Comment by harti2006** [comment] 2018-10-23 06:51
The nice thing about Spring Boot's [externalized configuration features](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config) is, that it already has first class support for different property sources, e.g. env variables, JVM system properties, program arguments, etc.

In your case, you can just try to pass the environment variable:
`SPRING_DATASOURCE_PASSWORD="{cipher}....."`. There is no need to re-map env variables in application.properties files, because of the [relaxed binding](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-relaxed-binding) feature.

**Comment by harti2006** [comment] 2018-11-02 10:46
@sfali Does the above mentioned solution work for you? If yes, please feel free to close this issue.

**Comment by pchainarong** [comment] 2018-11-07 07:10
Hi @harti2006, I have a similar question regarding this.
in my application.yaml, it consists of many spring profiles configuration. Even though we set spring.profiles.active:prod, the library tries to decrypt every cipher content. since we use different kms between different environment, then it throws error and stop processing.
I am not sure I have this setup properly or do you have any suggestion?

Regards,

**Comment by harti2006** [comment] 2018-11-07 07:43
@pchainarong Let me try to reproduce this behavior...

**Comment by pchainarong** [comment] 2018-11-07 07:47
the scenario is that you declare '{cipher}xx' in a default profile (let's say local and dev use the same key) and different '{cipher}yyy' in another profile.
I figure out that I need to move that encryped text and declare it in each env. it will work.

**Comment by harti2006** [comment] 2018-11-07 08:35
I created a small demo project: https://github.com/harti2006/spring-cloud-kms-profiles-demo. Please have a look at the unit tests to see and at the different config files located at `src/main/resources/config` to verify Spring's profile behavior.
I'm trying to add some decryption example there as well, but it is a bit tricky, since one needs to have access to my AWS account in order to run it.

**Comment by harti2006** [comment] 2018-11-07 09:21
@pchainarong Now I also added the KMS example tests to https://github.com/harti2006/spring-cloud-kms-profiles-demo. Pease see the README for details. Everything works as expected. Ciphers are only decrypted if they are contained in the currently activated profile.

Please also note, that using profiles for different environments is rather discouraged for cloud applications that follow the "12 factor app principles". Please see the section about [configuration](https://12factor.net/config)

**Comment by harti2006** [comment] 2019-04-01 08:50
Closing this thread due to inactivity. Feel free to reopen again if needed.

**Closed by harti2006** 2019-04-01 08:50 UTC

**Comment by lpfeup** [comment] 2019-11-02 20:11
@harti2006 I ran into the same issue. Are there any other alternatives other than specifying it via  `SPRING_DATASOURCE_PASSWORD="{cipher}....."`

**Comment by harti2006** [comment] 2019-11-04 07:49
@lpfeup I personally work a lot with Docker and Kubernetes. Environment variables are a perfect way to configure your Spring application in this setup. I don't see why it is a problem to set `SPRING_DATASOURCE_PASSWORD="{cipher}....."`, given you are already able to set environment vars like this `MYSQL_PASSWORD=...`. Can you please elaborate you issue?
Anyway, you can find a lot of other options how to configure an application here: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config
Please feel free to share some sample code and I'm happy to give you feedback on it.

**Comment by binodrajpandey** [comment] 2020-04-07 02:37
> relaxed binding



> The nice thing about Spring Boot's [externalized configuration features](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config) is, that it already has first class support for different property sources, e.g. env variables, JVM system properties, program arguments, etc.
> 
> In your case, you can just try to pass the environment variable:
> `SPRING_DATASOURCE_PASSWORD="{cipher}....."`. There is no need to re-map env variables in application.properties files, because of the [relaxed binding](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-relaxed-binding) feature.

I am not getting your point. How can I map `password: "{cipher} MYSQL_CONFIGDB_PASS"` ? It is not working.
